[project]
name = "multimodal-document-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jefferson Salvador", email = "jeffsalvador.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.14",
    "langchain-openai>=1.4.3",
    "python-dotenv>=1.2.2",
]

[project.scripts]
main = "multimodal_document_ai.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
